---
- name: Verify Ansible version is greater than 1.8.0 and not 1.9.0
  assert:
    that:
    - ansible_version | version_compare('1.8.0', 'ge')
    - ansible_version | version_compare('1.9.0', 'ne')
    - ansible_version | version_compare('1.9.0.1', 'ne')

- name: Determine if Atomic
  stat: path=/run/ostree-booted
  register: s
  changed_when: false

- name: Init the is_atomic fact
  set_fact:
    is_atomic: false

- name: Set the is_atomic fact
  set_fact:
    is_atomic: true
  when: s.stat.exists

- name: Gather Cluster facts
  openshift_facts:
