---
- name: Gather Cluster facts
  hosts: all
  gather_facts: no
  roles:
  - openshift_facts
  tasks:
  - openshift_facts:
      local_facts:
        cluster_id: "{{ openshift_cluster_id | default('default') }}"
        debug_level: "{{ openshift_debug_level | default(2) }}"
        hostname: "{{ openshift_hostname | default(None) }}"
        ip: "{{ openshift_ip | default(None) }}"
        public_hostname: "{{ openshift_public_hostname | default(None) }}"
        public_ip: "{{ openshift_public_ip | default(None) }}"
        use_openshift_sdn: "{{ openshift_use_openshift_sdn | default(None) }}"
        sdn_network_plugin_name: "{{ os_sdn_network_plugin_name | default(None) }}"
        deployment_type: "{{ deployment_type }}"
        use_fluentd: "{{ openshift_use_fluentd | default(None) }}"
        use_cluster_metrics: "{{ openshift_use_cluster_metrics | default(None) }}"
    register: result
  - debug: var=result
