---
- name: Cleanup logging deployment
  include: "{{ role_path }}/tasks/cleanup_logging.yaml"
  when: openshift_hosted_logging_cleanup | default(false) | bool

- name: Deploy logging
  include: "{{ role_path }}/tasks/deploy_logging.yaml"
  when: openshift_hosted_logging_deploy | default(false) | bool

- name: Upgrade logging
  include: "{{ role_path }}/tasks/upgrade_logging.yaml"
  when: openshift_hosted_logging_upgrade | default(false) | bool
